[programs.localnet]
oneirobot = "Oneirobot111111111111111111111111111111111"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node tests/oneirobot.js"
